### ISSUE TITLE
Windows Scaling shifts TagEveryDesktop out of the corner

### ISSUE THREAD

**Issue by bf-ryanalexander** [HealthITAU/TED#6]
If the device's Scaling is adjusted from the Windows "Recommended" setting, TED will not be in the corner anymore; have seen it just shifted horizontally, and have also seen it shifted directly diagonal from the corner. Have seen this behavior on Windows 10 22H2 and Windows 11 23H2. 
https://github.com/HealthITAU/TED/assets/150263565/497d67ce-d821-4c01-8dfe-c4db2f6a3dea
https://github.com/HealthITAU/TED/assets/150263565/c3df5fbc-2be9-4c70-8501-94430c04c1d6

**Comment by Yoshify** [comment]
Sorry for the wait. This should be fixed in V2!

**Comment by bf-ryanalexander** [comment]
Thanks for the update, seems like it is much more consistent now! However the issue of Scaling moving it out of the corner still persists. If I change my primary monitor's scaling (Settings > System > Display > Scale & layout > Scale) from the Recommended setting, the information will be moved diagonally upon re-write.
