### ISSUE TITLE
24H2: TED does not render, or just a quick flash

### ISSUE THREAD

**Issue by Sewef** [HealthITAU/TED#7]
Hey there.
Title is kinda self explanatory, TED does not render in W11 24H2.
It worked literally yesterday, my laptop updated tonight.
I tried compiling with latest NET Framework but nope.

**Comment by adammckay** [comment]
Sam issue here.  After updating to Windows 11 24H2, I am toast and the program doesn't do anything anymore.

**Comment by emike09** [comment]
Glad it's not just me. Sad day.

**Comment by Yoshify** [comment]
Sorry for the wait. This should be fixed in V2!

**Comment by acidos** [comment]
For me V2 doesn't solve the issue on Windows 11 IoT 24H2. Flashes and nothing is shown.
